### ISSUE TITLE
WARNING: Requested command 'create edge type 'was_located' as subclass of 'E'' must be executed outside active transaction

### ISSUE THREAD

**Issue by gjrwebber** [gjrwebber/spring-data-gremlin#20]
When running tests, the following warning is logged:

"WARNING: Requested command 'create edge type 'was_located' as subclass of 'E'' must be executed outside active transaction: the transaction will be committed and reopen right after it. To avoid this behavior execute it outside a transaction".

**Comment by compensator** [comment]
From what I've gathered, this should probably be INFO instead of WARNING.  OrientDB handles the issue of a schema change within a transaction for the developer by committing and exiting  transaction, executing the schema change, and opening a/the transaction, then continuing and issues a WARNING rather than INFO; it does this because schema changes are non-transactional.

**Comment by gjrwebber** [comment]
Thanks, I'll have a look anyway to see whether there is anything I can do.
